services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    hostname: api
#    restart: always
    ports:
      - "8080:8080"
    environment:
      - OAI_TYPE=openapi
      - OAI_URL=https://api.openai.com
      - OAI_KEY=sk-example